name: Testing

on:
  push:
    branches: [master]
    pull_request: [master]

jobs:
  build:

  runs-on: ubuntu-latest

  steps:
    - name: Setup PHP with intl
      uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: intl-70.1
